#!/bin/bash
. /home/bae/music/resources/m3dsrc/AutoDashboard/shell/env.sh

#svn模块名
svn_name=$1;
#产品名
online_name=$2;
#静态资源访问前缀
static_prefix=$3;
#静态资源目录
static_path=$4
#模板资源访问前缀
template_prefix=$5;
#模板资源目录
template_path=$6

echo "svn模块名：$svn_name";
echo "产品名：$online_name";
echo "静态资源访问前缀：$static_prefix";
echo "静态资源目录：$static_path";
echo "模板资源访问前缀：$template_prefix"
echo "模板资源目录：$template_path";

if [ "$svn_name" = "" ]; then
    die "模块名为空";
fi
#检查svn代码中是否存在该模块
[ -d "$BASE_DIR/src/trunk/fe/$svn_name" ] || die "不存在$svn_name模块";

path="$BASE_DIR/$BRANCH_TEMPLATE_NAME";
cd "$path";

(cd src && ln -snf "../../src/trunk/fe/$svn_name") || die "创建$svn_name模块软链接失败"; cd "$path";
#编译目录
(cd build && if ! [ -d "$svn_name" ]; then mkdir "$svn_name"; fi) || die "创建$svn_name模块编译目录失败"; cd "$path";

#wwwdata.test环境
(cd wwwdata.test/webroot && ln -snf "../../src/$svn_name/$static_path" "$static_prefix") || die "创建test环境静态资源软链接失败"; cd "$path";
(cd wwwdata.test/fe/templates_webapp && ln -snf "../../../src/$svn_name/$template_path" "$template_prefix") || die "创建test环境模板资源软链接失败"; cd "$path";

#wwwdata.build环境
(cd wwwdata.build/webroot && ln -snf "../../build/$svn_name" "$static_prefix") || die "创建build环境静态资源软链接失败"; cd "$path";
#build环境下每个模块目录包含的是test环境下src编译后的文件，故这里去掉前缀src
build_template_path=${template_path#*/};
#echo $build_template_path;
(cd wwwdata.build/fe/templates_webapp && ln -sfn "../../../build/$svn_name/$build_template_path" "$template_prefix") || die "创建build环境模板资源软链接失败"; cd "$path";

#写入module_config.php文件
cd "$BASE_DIR";
config_path="resources/m3dsrc/AutoDashboard/config/module_config.php";
array=",\'$svn_name\' => array(\'title\' => \'$svn_name\',\'ln_name\' => \'$svn_name\',\'module_name\' => \'$online_name\')";
(sed -i 's/\(\/\*#new_module#\*\/\)/'"${array}"'\1/' "$config_path") || die "写入配置失败"; cd "$BASE_DIR";
#svn提交
$SVNFE ci "$config_path" -m "commit by autoDashboard `date "+%Y-%m-%d %H:%M"`";

echo "添加成功";