#!/bin/bash

function replace(){
	grep -rl "$1" * | xargs -i sed -i "s/$1/$2/g" {};
}

export LANG="zh_CN.UTF8"
SVNFE="/home/bae/local/subversion/bin/svn --config-dir /home/bae/.svn-fe/";
COMMIT_LOG="autocommit.log";
PWD="$(pwd)";

#======add dev env configs by luoqin 20111130=====#
SRC_MERGE_CONFIG_DIR="${PWD}/src/fe-main/src/static/_m3d/imerge";
SRC_PREPROCESS_COUT_DIR="${PWD}/src/fe-main/src/static/_m3d/cout";
#======end add dev env configs by luoqin 20111130=====#

case "$1" in
	"app")
BUILD_DIR="${PWD}/src/fe-app/approot/build";
TMP_DIR="${PWD}/build/fe-app/app"
LOG_DIR="${PWD}/build/fe-app"
#../compile_new app #不再使用shell编译
	;;

	*)
BUILD_DIR="${PWD}/src/fe-main/build";
TMP_DIR="${PWD}/build/fe-main"
LOG_DIR="${PWD}/build/fe-main"
#../compile_new #不再使用shell编译
	;;
esac;

if ! [ -d "${TMP_DIR}" ];then
	echo "没有找到build目录，请编译通过后提交";
fi;


echo "提交前版本信息";
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++";
$SVNFE info "${BUILD_DIR}";
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++";
#mv "${LOG_DIR}/static/log.html" "log.html.bac"; #不使用shell编译，故编译日志不再需要
touch "${TMP_DIR}/${COMMIT_LOG}";
echo "删除多余文件";
( ( cd "${BUILD_DIR}" && find . -name ".svn" -prune -o  -print  &&  cd "${TMP_DIR}" && find . \( -name "templates_c" \) -prune -o  -print ) | sort | uniq -u  | while read line; do
	if [ -e "${BUILD_DIR}/${line}" ];then
		echo "svn del \"${BUILD_DIR}/${line}\"";
		$SVNFE del "${BUILD_DIR}/${line}";
		rm -rf "${BUILD_DIR}/${line}";
	fi;
done;) || exit -1;
rm "${TMP_DIR}/${COMMIT_LOG}";

echo "复制编译结果";

echo "cp ${TMP_DIR}/* ${BUILD_DIR} -r";
cp ${TMP_DIR}/* ${BUILD_DIR} -r;

echo "替换线下地址";
cd "${BUILD_DIR}" || exit -1;
replace "passport.rdtest" "passport";
cd -;

echo "提交SVN";

echo "svn add ${BUILD_DIR}/* --force";
$SVNFE add ${BUILD_DIR}/* --force;

echo "svn ci \"${BUILD_DIR}\" -m \"commit by autobuild `date \"+%Y-%m-%d %H:%M\"`\"";
$SVNFE ci "${BUILD_DIR}" -m "commit by autobuild `date "+%Y-%m-%d %H:%M"`";

#====拷贝生成小图配置到SVN, add by luoqin=====#
echo '';
echo "同步小图配置...";
#echo "删除多余文件";
#( ( cd "${SRC_MERGE_CONFIG_DIR}" && $SVNFE status -print |grep '!' | while read line; do
#       if [ -e "${SRC_MERGE_CONFIG_DIR}/${line}" ];then
#               echo "svn del \"${SRC_MERGE_CONFIG_DIR}/${line}\"";
#			$SVNFE del "${SRC_MERGE_CONFIG_DIR}/${line}";

echo "svn add ${SRC_MERGE_CONFIG_DIR}/* --force";
$SVNFE add ${SRC_MERGE_CONFIG_DIR}/* --force;

echo "svn ci \"${SRC_MERGE_CONFIG_DIR}\" -m \"commit by InstantMerge `date \"+%Y-%m-%d %H:%M\"`\"";
$SVNFE ci "${SRC_MERGE_CONFIG_DIR}" -m "commit by InstantMerge `date "+%Y-%m-%d %H:%M"`";

#====拷贝生成合图配置到SVN=============#
echo '';
echo "同步合图配置...";
echo "svn add ${SRC_PREPROCESS_COUT_DIR}/* --force";
$SVNFE add ${SRC_PREPROCESS_COUT_DIR}/* --force;

echo "svn ci \"${SRC_PREPROCESS_COUT_DIR}\" -m \"commit by InstantMerge `date \"+%Y-%m-%d %H:%M\"`\"";
$SVNFE ci "${SRC_PREPROCESS_COUT_DIR}" -m "commit by InstantMerge `date "+%Y-%m-%d %H:%M"`";

#mv  "log.html.bac" "${LOG_DIR}/static/log.html"; #不再使用shell编译，无log.html编译日志
