#!/bin/bash
##############################
# 清除不用的分支
##############################

. ./env.sh

cd "$BASE_DIR" || die "CD失败";

#显示全部FE分支
echo "显示全部FE分支:";
for item in $FE_MAIN_BRANCH_DIR/*; do
	del_tag="$item/.del";
	if [ -d "$item" ] || [ -f "$del_tag" ]; then
		#echo "$(basename "$item")" >> "$FE_BRANCH_ALL";
		basename $item;
		#rm -f "$del_tag";
	fi;
done;

#显示全部webapp分支:
echo "显示全部webapp分支:";
for item in $FE_WEBAPP_BRANCH_DIR/*; do
        del_tag="$item/.del";
        if [ -d "$item" ] || [ -f "$del_tag" ]; then
                #echo "$(basename "$item")" >> "$FE_BRANCH_ALL";
                basename $item;
                #rm -f "$del_tag";
        fi;
done;

#全部MBOX分支
#echo "显示全部MBOX分支:";
#for item in $FE_MBOX_BRANCH_DIR/*; do
#	del_tag="$item/.del";
#	if [ -d "$item" ] && [ -f "$del_tag" ]; then
#		#echo "$(basename "$item")" >> "$MBOX_BRANCH_ALL";
#		basename $item;
#		rm -f "$del_tag";
#	fi;
#done;

#显示全部RD分支
echo "显示全部RD分支:";
for item in $RD_MAIN_BRANCH_DIR/*; do
	del_tag="$item/.del";
	if [ -d "$item" ] || [ -f "$del_tag" ]; then
		#echo "$(basename "$item")" >> "$RD_BRANCH_ALL";
		basename $item;
		#rm -f "$del_tag";
	fi;
done;
