<?php 
return array (
  'config' => 
  array (
    '/static/images/testa.png' => 
    array (
      'width' => 606,
      'height' => 372,
      'top' => 756,
      'right' => 3,
      'bottom' => 1132,
      'left' => 3,
      'config' => 
      array (
        'id' => NULL,
        'repeat' => 'x',
        'float' => 'none',
        'min-width' => 0,
        'min-height' => 0,
        'padding-left' => 3,
        'padding-top' => 0,
        'padding-right' => 3,
        'padding-bottom' => 0,
        'border-left' => 0,
        'border-right' => 0,
        'border-top' => 0,
        'border-bottom' => 0,
      ),
    ),
    '/static/images/testc.png' => 
    array (
      'width' => 612,
      'height' => 384,
      'top' => 5,
      'right' => 13,
      'bottom' => 1888,
      'left' => 3,
      'config' => 
      array (
        'id' => NULL,
        'repeat' => 'none',
        'float' => 'none',
        'min-width' => 0,
        'min-height' => 0,
        'padding-left' => 3,
        'padding-top' => 5,
        'padding-right' => 3,
        'padding-bottom' => 5,
        'border-left' => 0,
        'border-right' => 0,
        'border-top' => 0,
        'border-bottom' => 0,
      ),
    ),
    '/static/images/testd.png' => 
    array (
      'width' => 612,
      'height' => 372,
      'top' => 1128,
      'right' => 0,
      'bottom' => 760,
      'left' => 0,
      'config' => 
      array (
        'id' => NULL,
        'repeat' => 'x',
        'float' => 'none',
        'min-width' => 0,
        'min-height' => 0,
        'padding-left' => 0,
        'padding-top' => 0,
        'padding-right' => 0,
        'padding-bottom' => 0,
        'border-left' => 0,
        'border-right' => 0,
        'border-top' => 0,
        'border-bottom' => 0,
      ),
    ),
    '/static/images/teste.png' => 
    array (
      'width' => 606,
      'height' => 372,
      'top' => 1500,
      'right' => 3,
      'bottom' => 388,
      'left' => 3,
      'config' => 
      array (
        'id' => NULL,
        'repeat' => 'x',
        'float' => 'none',
        'min-width' => 0,
        'min-height' => 0,
        'padding-left' => 3,
        'padding-top' => 0,
        'padding-right' => 3,
        'padding-bottom' => 0,
        'border-left' => 0,
        'border-right' => 0,
        'border-top' => 0,
        'border-bottom' => 0,
      ),
    ),
    '/static/images/testg.png' => 
    array (
      'width' => 600,
      'height' => 372,
      'top' => 384,
      'right' => 13,
      'bottom' => 1504,
      'left' => 0,
      'config' => 
      array (
        'id' => NULL,
        'repeat' => 'none',
        'float' => 'none',
        'min-width' => 0,
        'min-height' => 0,
        'padding-left' => 0,
        'padding-top' => 0,
        'padding-right' => 0,
        'padding-bottom' => 0,
        'border-left' => 0,
        'border-right' => 0,
        'border-top' => 0,
        'border-bottom' => 0,
      ),
    ),
    '/static/images/testh.png' => 
    array (
      'width' => 606,
      'height' => 384,
      'top' => 1876,
      'right' => 3,
      'bottom' => 16,
      'left' => 3,
      'config' => 
      array (
        'id' => NULL,
        'repeat' => 'x',
        'float' => 'none',
        'min-width' => 0,
        'min-height' => 0,
        'padding-left' => 3,
        'padding-top' => 4,
        'padding-right' => 3,
        'padding-bottom' => 4,
        'border-left' => 0,
        'border-right' => 0,
        'border-top' => 0,
        'border-bottom' => 0,
      ),
    ),
  ),
);