<?php
/**
 * Js处理器
 * User: zoujiawei
 * Date: 13-11-11
 * Time: 下午6:03
 * To change this template use File | Settings | File Templates.
 */

class JsPreprocess extends Preprocess {
    /**
     * 预处理开始，document.write合并
     * @return mixed|void
     */
    public function process() {
        trigger('process_js_start', $this);
        $this->handleDocumentWrite();
        $this->handleMediaResource();
    }

    /**
     * Js压缩
     * @return mixed|void
     */
    public function compress() {
        $compressor = Compressor::getInstance('js');
        $compressor->setContents($this->contents);
        $compressor->compress();
        $this->contents = $compressor->contents;
        $endInfo = PHP_EOL
            .'/** If u are interested in our code and would like to make it robust, just contact us^^ <@音乐前端> **/'.PHP_EOL
            .'/** Generated by M3D. **/';
        $this->contents .= $endInfo;
    }

    /**
     * 将document.write进来的文件合并
     */
    private function handleDocumentWrite() {
        $this->contents = preg_replace_callback(
            '/(?<!\\/{2})document\.write\\((\\\'|\\")<script(?:(?:\s+?[^>]+?)*?\s+?type=(\\\\?(?:\\\'|\\"))text\\/javascript\\2)?(?:\s+?[^>]+?)*?\s+?src=(\\\\?(?:\\\'|\\"))([^>\\s\\3]+?)\\3(?:(?:\s+?[^>]+?)*?\s+?type=\\\\?(\\\'|\\")text\\/javascript\\5)?[^>]*?>\\s*<\\/script>\\1\\);?/i',
            array($this, 'handle'),
            $this->contents
        );
    }

    private function handle($matches) {
        $path = Tool::getActualPath($matches[4]);
        $processor = new JsPreprocess($this->map);
        $processor->setFile(C('SRC.SRC_PATH').$path);
        $processor->process();

        trigger('js_import', $this, $processor);

        return $processor->getContents();
    }

    /**
     * 处理media资源，地址替换
     */
    private function handleMediaResource() {
        static $reg = null;
        if (is_null($reg)) {
            $processor = parent::getInstance('media');
            $mediaTypes = $processor->getOptions();
            $mediaTypes = comma_str_to_array($mediaTypes['type']);
            if (!empty($mediaTypes)) {
                $reg = '/(?<=[\'\"])(?:'.str_replace('/', '\\/', C('STATIC_VIRTUAL_PREFIX')).'[^\'\"\\\]*)\.(?:'.implode('|', $mediaTypes).')(?=[\'\"\\\])/';
            } else {
                $reg = false;
            }
        }

        if ($reg) {
            $this->contents = preg_replace_callback($reg, array($this, 'replaceMediaPath'), $this->contents);
        }
    }

    private function replaceMediaPath($matches) {
        $path = $matches[0];
        $aPath = Tool::getActualPath($path);
        if (isset($this->map['media'][$aPath])) {
            trigger('js_replace', $this, $aPath);
            return Tool::addCdn($this->map['media'][$aPath]);
        }
        return $path;
    }
}